### ISSUE TITLE
Magic Command Line - Finalise Structure of magic commands

### ISSUE THREAD

**Issue by krvikas1011** [Vikas-Open-Source/magic-command-line#17]
## Acceptance Criteria
- [x] Have a final common structure for the magic commands.
- [x] The final command is verified to be extensible for future changes.

Child of: https://github.com/Vikas-Open-Source/magic-command-line/issues/15

**Comment by krvikas1011** [comment]
The initial thought is to go with : `magic <resource_name> <action_name> <params>`

**Comment by shubhaangi04** [comment]
The structure that we have finalized is as follows:
`magic <resource_name> -a <action_name> -p <parameter_name>`

For example, if the user wants to create a file, then the command will look like:
`magic file -a create -p "C:\Temp\file.txt"`

The purpose of switch is that if the action_name consists of two or more words, or the parameter_name consists of two or more words, magic will know which words to consider for action_name or parameter_name respectively.
For example, if we want to create a folder recursively, then the action_name would be "create recursively".
There is no need of having a switch for <resource_name> because it will always come first.

**Comment by krvikas1011** [comment]
Completed and verified.

**Comment by krvikas1011** [comment]
Resource = Type/What do you want to act upon
Action = What action you want to perform on the resource
Params = Any metadata about the resource or the actions

A single magic command can have multiple words falling in each of these categories.
